# Generated by Django 3.2.5 on 2021-10-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='nome')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='preco')),
                ('photo', models.ImageField(upload_to='', verbose_name='foto')),
            ],
            options={
                'verbose_name': 'Produto',
            },
        ),
    ]
