# Generated by Django 3.2.7 on 2021-11-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='nome completo')),
                ('cpf', models.CharField(max_length=128, verbose_name='cpf')),
                ('nickname', models.CharField(max_length=128, unique=True, verbose_name='nickname')),
                ('password', models.CharField(max_length=128, verbose_name='senha')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('street', models.CharField(max_length=255, verbose_name='rua')),
                ('district', models.CharField(max_length=255, verbose_name='bairro')),
                ('number', models.CharField(default='S/N', max_length=128, verbose_name='número')),
                ('city', models.CharField(max_length=128, verbose_name='city')),
                ('complement', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento')], max_length=11, verbose_name='complemento')),
                ('reference_point', models.CharField(blank=True, max_length=255, null=True, verbose_name='ponto de referência')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
        ),
    ]
