# Generated by Django 3.2.7 on 2021-11-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente'},
        ),
    ]
