# Generated by Django 3.2.5 on 2021-12-01 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20211130_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(blank=True, default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='auth.user'),
            preserve_default=False,
        ),
    ]
