# Generated by Django 3.2.7 on 2021-12-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=144, verbose_name='serviço')),
                ('description', models.TextField(max_length=255, verbose_name='descrição')),
                ('value', models.FloatField(verbose_name='valor')),
            ],
        ),
    ]
