# Generated by Django 3.2.7 on 2021-12-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='data')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='home.client', verbose_name='client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='home.service', verbose_name='service')),
            ],
        ),
    ]
