# Generated by Django 3.2.7 on 2021-12-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='accomplished',
            field=models.BooleanField(default=False, verbose_name='executado'),
        ),
    ]
